# Permalinks
permalink:        pretty

# Setup
title:            Prabhav
tagline:          'My Personal Site'
description:      'Game Designer | Programmer | Technical Artist | sometimes make Music'
url:              https://prabhav2b.github.io
baseurl:          /

author:
  name:           'Prabhav Bhatnagar'
  url:            https://bsky.app/profile/probob.bsky.social



paginate:         5


# Custom vars
version:          0.2.0

github:
  repo:           https://bsky.app/profile/probob.bsky.social

  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate